config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'patients#index'
  get '/users', to: 'devise/registrations#new'
  resources :patients do
    get :chart, on: :collection
    get :search, on: :collection
    get :excel, on: :collection
  end
  #get '/search', action: :search, controller: 'patients'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/belong.rb
class Belong < ActiveHash::Base
  self.data = [
    { id: 1, name: '愛知県' },
    { id: 2, name: '名古屋市' },
    { id: 3, name: '千種保健センター' },
    { id: 4, name: '東保健センター' },
    { id: 5, name: '北保健センター' },
    { id: 6, name: '西保健センター' },
    { id: 7, name: '中村保健センター' },
    { id: 8, name: '中保健センター' },
    { id: 9, name: '昭和保健センター' },
    { id: 10, name: '瑞穂保健センター' },
    { id: 11, name: '熱田保健センター' },
    { id: 12, name: '中川保健センター' },
    { id: 13, name: '港保健センター' },
    { id: 14, name: '南保健センター' },
    { id: 15, name: '守山保健センター' },
    { id: 16, name: '緑保健センター' },
    { id: 17, name: '名東保健センター' },
    { id: 18, name: '天白保健センター' },
    { id: 19, name: '豊橋市保健所' },
    { id: 20, name: '一宮市保健所' },
    { id: 21, name: '豊田市保健所' },
    { id: 22, name: '岡崎保健所' },
    { id: 23, name: '瀬戸保健所' },
    { id: 24, name: '春日井保健所' },
    { id: 25, name: '江南保健所' },
    { id: 26, name: '清須保健所' },
    { id: 27, name: '津島保健所' },
    { id: 28, name: '半田保健所' },
    { id: 29, name: '知多保健所' },
    { id: 30, name: '衣浦東部保健所' },
    { id: 31, name: '西尾保健所' },
    { id: 32, name: '新城保健所' },
    { id: 33, name: '豊川保健所' },
  ]

  include ActiveHash::Associations
  has_many :devise
  has_many :patients
end

app/models/patient.rb
class Patient < ApplicationRecord
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :belong
  belongs_to :prefecture  
  belongs_to :user
  
    #携帯番号の入力は任意だが、空欄か正規表現ハイフンなしの10桁か11桁
  VALID_EMAIL_REGEX = /\A\d{10}$|^\d{11}\z/
  with_options format: { with: VALID_EMAIL_REGEX, allow_blank: true } do
    validates :phone01 
    validates :phone02
    validates :phone03
    validates :phone04
  end

  with_options presence: true do
    validates :kana01
    validates :gender
    validates :belong_id
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '不明' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, 
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, 
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, 
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, 
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, 
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, 
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, 
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, 
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, 
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
]

include ActiveHash::Associations
has_many :patients

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :belong
  belongs_to :prefecture


  has_many :patients
  
  with_options presence: true do
    validates :belong_id
    validates :birth_date
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }
      
      with_options format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/} do
        validates :first_name
        validates :last_name
      end
      
        with_options format: { with: /\A[\p{katakana} ー－&&[^ -~｡-ﾟ]]+\z/} do
          validates :last_name_kana 
          validates :first_name_kana
        end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

private

def configure_permitted_parameters ##email,passwordはデフォルトで搭載済み
  devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :belong_id, :birth_date])
end

def basic_auth
  authenticate_or_request_with_http_basic do |username, password|
    username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
  end
 end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :patient_set, only: [:edit, :show, :update]
  before_action :authenticate_user!, except: [:index]
  before_action :search_product, only: [:excel, :chart, :search]


def index
  @patients = Patient.all.order("created_at DESC")
  @patients_count = Patient.group_by_day(:created_at).size
  @patient_today = Patient.where(created_at: Date.today.all_day).count
end

def new
  @patient = Patient.new
end

def create
  @patient = Patient.new(patient_params)
  if @patient.save
    redirect_to root_path
  else
    render :new
  end
end

def edit
end

def update
  if @patient.update(patient_params)
    redirect_to patient_path
  else
    render :edit
  end
end

def chart
  @patients = Patient.all.order("created_at DESC")
end

def search
  @patients = Patient.all.order("created_at DESC")
  @results = @q.result
end

def show
end

#excelについて
def excel
  @results = @q.result
  respond_to do |format|
    format.html
    format.xlsx { |html| html.tablet
        response.headers['Content-Disposition'] = 'attachment; filename="患者リスト"'+ Time.zone.now.strftime('%Y%m%d%H%M%S') + '.xlsx'
    }
  end
end

private

def patient_params
  params.require(:patient).permit(:kana01, :name01, :gender, :age, :nationality, :postcode, :prefecture_id, :city, :town, :phone01, :phone02, :email, :belong_id, :company, :location, :phone03, :kana02, :name02, :relationship, :phone04, :number, :free).merge(user_id: current_user.id)
end

def search_product
  @q = Patient.ransack(params[:q])
end

def patient_set
  @patient = Patient.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HMC2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
  <!-- bootstrapより拝借 -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <body>
    <%#p class="notice"><%= notice %></p>
    <%#p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/patients/chart.html.erb
<%= render "shared/header" %>

  <h3>患者検索</h3>
    <%= search_form_for @q, url: search_patients_path do |f| %>
    <%= f.label :kana01_cont, '患者フリガナ' %>
    <%= f.search_field :kana01_cont %>
    <br>
    <%= f.label :gender, '性別' %>
    <%= f.radio_button :gender_eq, '' %>指定なし
    <%= f.radio_button :gender_eq, '男' %>男
    <%= f.radio_button :gender_eq, '女' %>女
    <%= f.radio_button :gender_eq, '不明' %>不明
    <br>
    <%= f.label :age_cont, '年齢' %>
    <%= f.radio_button :age, '10歳未満' %>10歳未満
    <%= f.radio_button :age, '10歳代' %>10歳代
    <%= f.radio_button :age, '20歳代' %>20歳代
    <%= f.radio_button :age, '30歳代' %>30歳代
    <%= f.radio_button :age, '40歳代' %>40歳代
    <%= f.radio_button :age, '50歳代' %>50歳代
    <%= f.radio_button :age, '60歳代' %>60歳代
    <%= f.radio_button :age, '70歳代以上' %>70歳代以上
    <br>
    <%= f.label :belong_id_cont, '担当保健所' %>
    <%= f.collection_select(:belong_id_eq, Belong.all, :id, :name, include_blank: '指定なし' )%>
    <br>
    <%= f.submit '検索' %>
    <% end %>
</form>

<%#患者一覧を表形式で表示%>
<span class="btn">患者一覧(Excel出力可能)</span>
<%= button_to excel_patients_path(format: :xlsx), method: :get do %>
      エクセル出力
<% end %>
<table class="table table-striped">
  <thead>
    <tr align="center">
      <th scope="col">No.</th>
      <th scope="col">患者フリガナ</th>
      <th scope="col">患者氏名</th>
      <th scope="col">性別</th>
      <th scope="col">年齢</th>
      <th scope="col">担当保健所</th>
    </tr>
  </thead>
  <tbody>
      <% @patients.each do |patient| %>
    <tr align="center">
      <td><%= patient.id %></td>
      <td><%= link_to patient.kana01, patient_path(patient.id) %></td>
      <td><%= patient.name01 %></td>
      <td><%= patient.gender %></td>
      <td><%= patient.age %></td>
      <td><%= patient.belong.name %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/patients/index.html.erb
<%= render "shared/header" %>

<!-- グラフ -->
<div class="alert alert-primary" role="alert">
  <%= Date.today %>  愛知県の感染状況
</div>
<div class="main">
  <label class="text-user">新規感染者数推移（総人数：<%= @patients.count %>）</label>
  <div class="graph">
    <%= line_chart @patients_count, download: true, colors: ['#FF4F02'] %>
  </div>
</div>
<div class="main">
  <label class="text-user">感染者年代別割合（総人数：<%= @patients.count %>)</label>
  <div class="graph">
   <%= pie_chart Patient.group(:age).count, donut: true, suffix: "%" %>
  </div>
</div>
<div class="main">
  <label class="text-user">感染者男女割合（総人数：<%= @patients.count %>)</label>
  <div class="graph">
    <%= pie_chart Patient.group(:gender).count, colors: ["gray","pink","blue"] %>
  </div>
</div>

app/views/patients/new.html.erb
<%= render "shared/header" %>

<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <%= form_with model: @patient, url: patients_path, local: true do |f|%>
      <h2>新規患者の登録</h2>
      <h4>New Patient Registration</h4>
      <%= render 'shared/error_messages', model: f.object %>
    </div>
    <div class='account-page__inner--right user-form'>
        <div class='field'>
          <label class='field-label'>フリガナ(全角)</label>
          <span class="indispensable">必須</span>
          <div class='field-input'>
            <%= f.text_field :kana01, class:"input-name", id:"kana01", placeholder:"例) アイチタロウ" %>
          </div>
        </div>
         <div class='field'>
          <label class='field-label'>お名前(全角)</label>
          <div class='field-input'>
            <%= f.text_field :name01, class:"input-name", id:"name01", placeholder:"例) 愛知太朗" %>
          </div>
        </div>
        <div class='field'>
          <label class='field-label'>性別</label>
          <span class="indispensable">必須</span>
          <br class='field-input'>
            <%= f.radio_button :gender, '男' %>男
            <%= f.radio_button :gender, '女' %>女
            <%= f.radio_button :gender, '不明' %>不明
          <br>
        </div>
        <div class='field'>
          <label class='field-label'>年齢</label>
          <div class='field-input'>
            <%= f.radio_button :age, '10歳未満' %>10歳未満
            <%= f.radio_button :age, '10歳代' %>10歳代
            <%= f.radio_button :age, '20歳代' %>20歳代
            <%= f.radio_button :age, '30歳代' %>30歳代
            <%= f.radio_button :age, '40歳代' %>40歳代
            <%= f.radio_button :age, '50歳代' %>50歳代
            <%= f.radio_button :age, '60歳代' %>60歳代
            <%= f.radio_button :age, '70歳代以上' %>70歳代以上
          </div>
        </div>
        <div class='field'>
          <label class='field-label'>国籍</label>
          <div class='field-input'>
            <%= f.text_field :nationality, class:"input-name", id:"nationality" %>
          </div>
        </div>
         <div class='field'>
          <label class='field-label'>郵便番号</label>
          <div class='field-input'>
            <%= f.text_field :postcode, class:"input-name", id:"postcode", placeholder:"例) 123-4567" %>
          </div>
        </div>
        <div class='field'>
           <label class='field-label'>現住所</label>
           <i>都道府県</i>
          <div class='field-input'>
            <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {selected: 24}, {class:"input_name", id:"prefecture_id"}) %>
          </div>
        </div>
        <div class='field'>
          <label class='field-label'>現住所</label>
          <i>市町村</i>
          <div class='field-input'>
            <%= f.text_field :city, class:"input-name", id:"city", placeholder:"例) 〇〇市〇〇町" %>
          </div>
        </div>
        <div class='field'>
          <label class='field-label'>現住所</label>
          <i>丁目</i>
          <div class='field-input'>
            <%= f.text_field :town, class:"input-name", id:"town", placeholder:"例) 〇〇1-1-1" %>
          </div>
        </div>
        <div class='field'>
        <label class='field-label'>電話番号</label>
          <i>メイン</i>
          <div class='field-input'>
            <%= f.text_field :phone01, class:"input-name", id:"phone01", placeholder:"例) 0901234567" %>
          </div>
        </div>
        <div class='field'>
        <label class='field-label'>電話番号</label>
          <i>サブ</i>
          <div class='field-input'>
            <%= f.text_field :phone02, class:"input-name", id:"phone02", placeholder:"例) 0901234567" %>
          </div>
        </div>
        <div class='field'>
          <label class='field-label'>Eメール</label>
          <div class='field-input'>
            <%= f.text_field :email, class:"input-name", id:"email" %>
          </div>
        </div>
        <div class='field'>
           <label class='field-label'>担当保健所</label>
           <span class="indispensable">必須</span>
          <div class='field-input'>
            <%= f.collection_select(:belong_id, Belong.all, :id, :name, {}, {class:"input_name", id:"belong_id"}) %>
          </div>
        </div>
        <div class='field'>
          <p>勤務先または学校など</p>
          <label class='field-label'>勤務先</label>
          <div class='field-input'>
            <%= f.text_field :company, class:"input-name", id:"company", placeholder:"例) 〇〇株式会社〇〇支店"%>
          </div>
        </div>
        <div class='field'>
          <label class='field-label'>所在地</label>
          <div class='field-input'>
            <%= f.text_field :location, class:"input-name", id:"location", placeholder:"例) 〇〇市〇〇区〇〇1-1-1"%>
          </div>
        </div>
        <div class='field'>
        <label class='field-label'>電話番号</label>
          <div class='field-input'>
            <%= f.text_field :phone03, class:"input-name", id:"phone03", placeholder:"例) 0901234567" %>
          </div>
        </div>
        <div class='field'>
          <p>緊急連絡先</p>
          <label class='field-label'>患者フリガナ(全角)</label>
          <div class='field-input'>
            <%= f.text_field :kana02, class:"input-name", id:"kana02", placeholder:"例) アイチタロウ" %>
          </div>
        </div>
         <div class='field'>
          <label class='field-label'>氏名(全角)</label>
          <div class='field-input'>
            <%= f.text_field :name02, class:"input-name", id:"name02", placeholder:"例) 愛知太朗" %>
          </div>
        </div>
        <div class='field'>
          <label class='field-label'>続柄</label>
          <div class='field-input'>
            <%= f.text_field :relationship, class:"input-name", id:"name02", placeholder:"例) 父、娘など" %>
          </div>
        </div>
        <div class='field'>
        <label class='field-label'>電話番号</label>
          <div class='field-input'>
            <%= f.text_field :phone04, class:"input-name", id:"phone04", placeholder:"例) 0901234567" %>
          </div>
        </div>
        <div class='field'>
        <label class='field-label'>保健所ID</label>
          <i>管理番号</i>
          <div class='field-input'>
            <%= f.text_field :number, class:"input-name", id:"number", placeholder:"例) 21220" %>
          </div>
        </div>
        <label class='field-label'>自由記載欄</label>
          <i>(ご自由に記載してください)</i>
          <div class='field-input'>
            <%= f.text_area :free, class:"input-name", id:"free", rows: "6", placeholder:"例) この方は外国籍の方で、日本語での意思疎通が難しい。また、親族などおらず会社の責任者が緊急連絡先となっている。" %>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "患者登録", class: 'btn'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/patients/search.html.erb
<%= render "shared/header" %>


<div class="alert alert-primary" role="alert">
  検索結果表示
</div>

<% if @results.length !=0 %>
<table class="table table-striped">
  <thead>
    <tr align="center">
      <th scope="col">No.</th>
      <th scope="col">患者フリガナ</th>
      <th scope="col">患者氏名</th>
      <th scope="col">性別</th>
      <th scope="col">年齢</th>
      <th scope="col">担当保健所</th>
    </tr>
  </thead>
  <tbody>
      <% @results.each do |patient| %>
    <tr align="center">
      <td><%= patient.id %></td>
      <td><%= link_to patient.kana01, patient_path(patient.id) %></td>
      <td><%= patient.name01 %></td>
      <td><%= patient.gender %></td>
      <td><%= patient.age %></td>
      <td><%= patient.belong.name %></td>
    </tr>
    <% end %>
    <% else %>
    該当の患者はいません
    <% end %>
  </tbody>
  
</table>

app/views/patients/show.html.erb
<%= render "shared/header" %>

<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <%= form_with model: @patient, local: true do |f|%>
      <h2>患者情報の詳細</h2>
      <h4>Patient Data</h4>
      <div class='actions'>
      <%= link_to "編集", edit_patient_path, method: :get, class: 'btn' %>
    </div>
    </div>
  <div class='account-page__inner--right user-form'>
    <div class='field'>
      <table class="table">
      <tbody>
      <tr>
      <th scope="col">フリガナ</label>
      <td class="input-name"><%= @patient.kana01 %></td>
      </tr>
      <tr>
      <th class='detail-patient'>氏名</label>
      <td class="input-name"><%= @patient.name01 %></td>
      </tr>
      <tr>
      <th class='detail-patient'>性別</label>
      <td class="input-name"><%= @patient.gender %></td>
      </tr>
      <tr>
      <th class='detail-patient'>年齢</label>
      <td class="input-name"><%= @patient.age %></td>
      </tr>
      <tr>
      <th class='detail-patient'>国籍</label>
      <td class="input-name"><%= @patient.nationality %></td>
      </tr>
      <tr>
      <th class='detail-patient'>郵便番号</label>
      <td class="input-name"><%= @patient.postcode %></td>
      </tr>
      <tr>
      <th class='detail-patient'>現住所（都道府県）</label>
      <td class="input-name"><%= @patient.prefecture.name %></td>
      </tr>
      <tr>
      <th class='detail-patient'>現住所（市町村）</label>
      <td class="input-name"><%= @patient.city %></td>
      </tr>
      <tr>
      <th class='detail-patient'>現住所（丁目）</label>
      <td class="input-name"><%= @patient.town %></td>
      </tr>
      <tr>
      <th class='detail-patient'>電話番号（メイン）</label>
      <td class="input-name"><%= @patient.phone01 %></td>
      </tr>
      <tr>
      <th class='detail-patient'>電話番号（サブ）</label>
      <td class="input-name"><%= @patient.phone02 %></td>
      </tr>
      <tr>
      <th class='detail-patient'>Eメール</label>
      <td class="input-name"><%= @patient.email %></td>
      </tr>
      <tr>
      <th class='detail-patient'>担当保健所</label>
      <td class="input-name"><%= @patient.belong.name %></td>
      </tr>
      <tr>
      <th class='detail-patient'>勤務先または学校</label>
      <td class="input-name"><%= @patient.company %></td>
      </tr>
      <tr>
      <th class='detail-patient'>所在地</label>
      <td class="input-name"><%= @patient.location %></td>
      </tr>
      <tr>
      <th class='detail-patient'>電話番号</label>
      <td class="input-name"><%= @patient.phone03 %></td>
      </tr>
      <th class='detail-patient'>緊急連絡先(氏名フリガナ)</label>
      <td class="input-name"><%= @patient.kana02 %></td>
      </tr>
      <tr>
      <th class='detail-patient'>氏名</label>
      <td class="input-name"><%= @patient.name02 %></td>
      </tr>
      <tr>
      <th class='detail-patient'>続柄</label>
      <td class="input-name"><%= @patient.relationship %></td>
      </tr>
      </tr>
      <th class='detail-patient'>電話番号</label>
      <td class="input-name"><%= @patient.phone04 %></td>
      </tr>
      <tr>
      <th class='detail-patient'>保健所ID</label>
      <td class="input-name"><%= @patient.number %></td>
      </tr>
      <tr>
      <th class='detail-patient'>備考</label>
      <td class="input-name"><%= @patient.free %></td>
      </tr>
      </tbody>
      </div>
    <% end %>
    </div>
</div>
    </div>
      

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Headers - 15</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <!-- Header Start -->
    <header class="site-header">
      <div class="wrapper site-header__wrapper">
        <div class="brand">HMC2</div>
      </div>
        <nav class="nav">
          <ul class="nav__wrapper">
            <li><%= link_to 'ホーム', root_path, class: "nav__item" %></li>
            <li><%= link_to '患者情報登録', new_patient_path, class: "nav__item" %></li>
            <li><%= link_to '患者情報検索', chart_patients_path, class: "nav__item" %></li>
            <% if user_signed_in? %>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav__item"%></li>
            <% else %>
            <li><%= link_to 'ログイン', new_user_session_path, class: "nav__item" %></li>
            <% end %>
          </ul>
        </nav>
    </header>
    <!-- Header End -->

  </body>
</html>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>